APT::FTPArchive::Release::Origin "spotifast-apt";
APT::FTPArchive::Release::Label "spotifast-apt";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Unofficial Spotifast packages for Ubuntu 22.04 and newer";
